// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_buN-B5IrQCk3-YseFpcF2hN0Axl6QLY',
    appId: '1:163679844251:web:9f2299d146ad9f0abf533e',
    messagingSenderId: '163679844251',
    projectId: 'e-commerce-app-d1e29',
    authDomain: 'e-commerce-app-d1e29.firebaseapp.com',
    storageBucket: 'e-commerce-app-d1e29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFDuSjtHu0vHURLqqlyNTGLxMmcbVdYBQ',
    appId: '1:163679844251:android:974d28a452194253bf533e',
    messagingSenderId: '163679844251',
    projectId: 'e-commerce-app-d1e29',
    storageBucket: 'e-commerce-app-d1e29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVrhBgMlRVJbiXy9LX1xiSGE4yWBWCzC4',
    appId: '1:163679844251:ios:aea320c01b98837abf533e',
    messagingSenderId: '163679844251',
    projectId: 'e-commerce-app-d1e29',
    storageBucket: 'e-commerce-app-d1e29.appspot.com',
    iosClientId: '163679844251-jvb5i9rqhoikpe4u0ulo3aibd1egbvau.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginandsignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_buN-B5IrQCk3-YseFpcF2hN0Axl6QLY',
    appId: '1:163679844251:web:4d1fc54f06c658cfbf533e',
    messagingSenderId: '163679844251',
    projectId: 'e-commerce-app-d1e29',
    authDomain: 'e-commerce-app-d1e29.firebaseapp.com',
    storageBucket: 'e-commerce-app-d1e29.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVrhBgMlRVJbiXy9LX1xiSGE4yWBWCzC4',
    appId: '1:163679844251:ios:aea320c01b98837abf533e',
    messagingSenderId: '163679844251',
    projectId: 'e-commerce-app-d1e29',
    storageBucket: 'e-commerce-app-d1e29.appspot.com',
    iosClientId: '163679844251-jvb5i9rqhoikpe4u0ulo3aibd1egbvau.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginandsignup',
  );

}